Repository Tevy-B/valetbike, pull requests merged in 2021-12, with the labels that each got.

#66 no login/signup users can still see the bike
  app/views/bikes/show.html.erb
Labels: 15 minutes

#67 redirect the user to login
  app/views/bikes/show.html.erb
Labels: 5 minutes

#68 style changes
  app/assets/images/image_2.jpg
  app/assets/images/image_4.jpg
  app/assets/images/image_5.jpg
  app/assets/images/image_6.jpg
  app/views/billings/VISA.html.erb
  app/views/billings/mastercard.html.erb
  app/views/billings/new.html.erb
  app/views/billings/show.html.erb
  app/views/devise/registrations/edit.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/home/instruction.html.erb
Labels: 3.75hr

#69 style clean up
  app/views/bikes/return.html.erb
  app/views/bikes/returnConfirm.html.erb
  app/views/bikes/show.html.erb
  app/views/bikes/unlock.html.erb
  app/views/bikes/unlockConfirm.html.erb
  app/views/layouts/_header.html.erb
Labels: 1 hours
