Repository Tevy-B/valetbike, pull requests merged in 2021-11, with the labels that each got.

#31 make current station id of bike matches station id
  app/controllers/bikes_controller.rb
  app/views/bikes/show.html.erb
  app/views/stations/_row.html.erb
Labels: 2 hours

#32 nav bar, new sign up, new log in, edit profile, and sign out page
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/home.css
  app/controllers/home_controller.rb
  app/helpers/home_helper.rb
  app/models/user.rb
  app/views/devise/confirmations/new.html.erb
  app/views/devise/mailer/confirmation_instructions.html.erb
  app/views/devise/mailer/email_changed.html.erb
  app/views/devise/mailer/password_change.html.erb
  app/views/devise/mailer/reset_password_instructions.html.erb
  app/views/devise/mailer/unlock_instructions.html.erb
  app/views/devise/passwords/edit.html.erb
  app/views/devise/passwords/new.html.erb
  app/views/devise/registrations/edit.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/devise/shared/_error_messages.html.erb
  app/views/devise/shared/_links.html.erb
  app/views/devise/unlocks/new.html.erb
  app/views/home/index.html.erb
  app/views/layouts/_alert.html.erb
  app/views/layouts/_header.html.erb
  app/views/layouts/_notice.html.erb
  app/views/layouts/application.html.erb
  app/views/layouts/originalApplication.html.erb
  app/views/stations/index.html.erb
  config/environments/development.rb
  config/environments/production.rb
  config/initializers/devise.rb
  config/locales/devise.en.yml
  config/routes.rb
  db/migrate/20211111052245_devise_create_users.rb
  db/schema.rb
  test/controllers/home_controller_test.rb
  test/fixtures/users.yml
  test/models/user_test.rb
Labels: 4.25hr

#57 Add markers to map
  app/assets/javascripts/application.js
  app/assets/javascripts/map.js
  app/assets/stylesheets/application.css
  app/assets/stylesheets/stations.css
  app/controllers/stations_controller.rb
  app/views/stations/index.html.erb
  config/application.rb
Labels: 3.75hr
